[package]
name = "oxyclock"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {git = "https://github.com/iced-rs/iced", branch = "master", features = ["debug", "tokio"]}
notify-rust = "4.11.3"
rodio = "0.19.0"

[profile.release]
codegen-units = 1
lto = "fat"
